version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm


      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
  heroku_deploy:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
      - hold:
          type: approval
          requires:
            - ci
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - hold
          filters:
            branches:
              only: 
                - main
                - master
